discord:
    client: "CLIENT ID"
    secret: "CLIENT SECRET"
    token: "AUTH TOKEN"
imgur:
    client_id: "CLIENT ID"
    client_token: "TOKEN"
weather:
    api_key: "API_KEY"
plugins:
    - "cat"
    - "imgur"
    - "joke"
    - "text"
    = "weather"
